[package]
name = "port_knocking"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.213", features = ["derive"]}
serde_json = "1.0.128"
tokio = {version = "1.0", features = ["full"]}
axum = "0.7.5"